---
title: "Game show data"
output: html_notebook
---
```{r}
data<-read.csv('../20060455_Data.csv')
# clean dataset externally with excel
data$Gender_m <- ifelse(data$Gender == "M", 1,0)
data$Gender_f <- ifelse(data$Gender == "F", 1,0)
data$Education_h <- ifelse(data$Education == "H", 1,0)
data$Education_l <- ifelse(data$Education == "L", 1,0)
data$Deal...No.Deal_D <- ifelse(data$Deal...No.Deal == "D", 1,0)
data$Deal...No.Deal_ND <- ifelse(data$Deal...No.Deal == "ND", 1,0)
numeric_data<-subset(data, select= -c(ID.Number, Broadcast.Date, Name, Education, Gender, Deal...No.Deal))
summary(data)
```
```{r}
summary(numeric_data)
```
```{r}
cor(numeric_data)
heatmap(cor(numeric_data))
```

```{r}
no_rounds<-subset(numeric_data, select = -c(X0.01, X0.2, X0.5, X1, X5, X10, X20, X50, X100, X500, X1000, X2500, X5000, X7500, X10000, X25000, X50000, X75000, X100000, X200000, X300000, X400000, X500000, X1000000, X2500000, X5000000))
heatmap(cor(no_rounds))
```




```{r}
prediction_one<-lm(Amount.Won ~ Age+Stop.Round+Gender_f+Gender_m+Education_h+Education_l, data=no_rounds)
summary(prediction_one)
```




```{r}
cleaned<-read.csv('../gameData_clean.csv')
summary(cleaned)
prediction_two<-lm(Amount.Won ~ Age+Stop.Round+Education+Gender, data=no_rounds)
summary(prediction_two)
```












